baseURL: "https://nivins.in/"
languageCode: "en-us"
title: "Welcome !"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
    #Dropdown menu
      #- identifier: dropdown
       #title: Example dropdown menu
       #name: Dropdown
       #weight: 3
       #- identifier: dropdown1
         # title: example dropdown 1
         #name: example 1
          #url: /#
         #parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Nivin S"
  description: A 16 y/o dev's Profile
  # staticPath: ""  # The path to serve the static files from
  favicon: "img/Icon.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    #disableThemeToggle: false
    #defaultTheme: "dark" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

   # darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor: 
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "NivinS." # Brand name for the brand | default is the title variable
    disableSearch: true
     # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Nivin S Vysakh"
    subtitle: "I like to Learn New Skills !"
    content: "A passionate : Web developer | Discord Bot developer | Open Source Contributor"
    image: "img/Hero1.jpg"
    bottomImage:
      enable: true
      #roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Explore my Work"
      url: "https://github.com/ilynivin"
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-twitter
          url: https://twitter.com/Nivin389
      customIcons:
        - icon: img/icons/insta.png
          url: https://www.instagram.com/nivinvysakh/
        - icon: img/icons/codepen.png
          url: https://codepen.io/Nivin389
        - icon: img/icons/blog.png
          url: https://blognivins.netlify.app/

  # About
  about:
    enable: true
    title: "About Me 👑"
    image: "img/profile.jpeg"
    content: |-
      I am a 16 yr web developer | Discord BOT Developer . I am a tec person who loves coding and Gaming.

      Currently looking to collaborate with others & Learing NewSkills.
    skills:
      enable: true
      title: "My Skills"
      items:
        - "HTML"
        - "Astro.js"
        - "HUGO"
        - "Python"
        - "C"
        - "Lua"



  # Education
  education:
    enable: false
    # title: "Custom Name"
    index: false
    items:
      - title: "Secondary Education "
        school:
          name: "Jyothi Nivas Public School"
          url: "http://jyothinivasaluva.com/"
        date: "2012 - 2024"
        content: |-
          My Activities 
            - Member of  Waste management club 🌎
            - Took Oath of "Say No to Drugs" 🚭
            - Participated in School Youth festival 👓

# projects
  projects:
    enable: true
    title: "My Works 🌌"
    items:
      - title: 📰 | Hugo Blog 
        content: A Blog Webiste Made from Scratch with the Help of Hugo .
        image: img/projectpic/BlogProfile.png
        featured:
          name: Take a Look :P
          link: https://blognivins.netlify.app/
        badges:
          - "Hugo"
          - "Blog"
        links:
          - icon: fab fa-github
            url: https://github.com/ilynivin

      - title: 🌑 | Xelyer 
        content: My First Discord Bot from scratch with discord.py
        image:  img/projectpic/Xelyer.png
        featured:
          name: Add Your Server
          link: https://discord.com/oauth2/authorize?client_id=1111316333666254878&permissions=534723950656&scope=bot
        badges:
          - "Discord"
          - "JokeBot"
          - "Discord.py"
        links:
          - icon: fab fa-github
            url: https://github.com/Xelyer

          

      - title: 🤖 | Chat Bot
        content: My Second Discord Bot with Chat-GPT Turbo and Discord.py .
        image: img/projectpic/aibot.png
        featured:
          name: Source Code
          link: https://github.com/ilynivin/DiscordAi
        badges:
          - "Discord"
          - "ChatGPT"
          - "Discord.py"
        links:
          - icon: fab fa-github
            url: https://github.com/ilynivin/DiscordAi

  achievements:
    enable: true
    title: "Certifications ✨"
    items:
      - title: Certified Game Developer (CGD)
        content: "Year : 2021"
        url: https://www.whitehatjr.com/




  #Contact
  contact:
    enable: true
    title: "Message Me 📫"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: nivinvysakh2020@outlook.com
    btnName: Mail me


  footer:
    socialNetworks:
      github: https://github.com/ilynivin
      twitter: https://twitter.com/Nivin389
      instagram: https://www.instagram.com/nivinvysakh/

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved to Nivin S Vysakh 2024-2026"
    pageNotFound: "Ops! What Did you do."
    
